import {
  NAV_ITEM_TYPE_TITLE,
  NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant';
import { ADMIN, USER } from '@/constants/roles.constant';
import type { NavigationTree } from '@/@types/navigation';

const soarNavigationConfig: NavigationTree[] = [
  {
    key: '',
    path: '',
    title: ' ',
    translateKey: '',
    icon: ' ',
    type: NAV_ITEM_TYPE_TITLE,
    authority: [ADMIN, USER],
    subMenu: [
      {
        key: 'soar.dashboard',
        path: `/dashboard`,
        title: 'Dashboard',
        translateKey: 'nav.soar.dashboard',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: 'soar.transactions',
        path: '',
        title: 'Transactions',
        translateKey: 'nav.soar.transactions',
        icon: 'transaction',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
        disabled: true,
      },

      {
        key: 'soar.accounts',
        path: '',
        title: 'Accounts',
        translateKey: 'nav.soar.accounts',
        icon: 'account',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
        disabled: true,
      },
      {
        key: 'soar.Investments',
        path: '',
        title: 'Investments',
        translateKey: 'nav.soar.Investments',
        icon: 'investment',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
        disabled: true,
      },
      {
        key: 'soar.creditCards',
        path: '',
        title: 'Credit Cards',
        translateKey: 'nav.soar.creditCards',
        icon: 'credit',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
        disabled: true,
      },
      {
        key: 'soar.loans',
        path: '',
        title: 'Loans',
        translateKey: 'nav.soar.loans',
        icon: 'loan',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
        disabled: true,
      },
      {
        key: 'soar.services',
        path: '',
        title: 'Services',
        translateKey: 'nav.soar.services',
        icon: 'services',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
        disabled: true,
      },
      {
        key: 'soar.myPrivilages',
        path: '',
        title: 'My Privilages',
        translateKey: 'nav.soar.myPrivilages',
        icon: 'econometrics',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
        disabled: true,
      },

      {
        key: 'soar.setting',
        path: 'account/settings',
        title: 'Setting',
        translateKey: 'nav.soar.setting',
        icon: 'setting',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
    ],
  },
];

export default soarNavigationConfig;
