/* eslint-disable no-undef */
/** @type {import('tailwindcss').Config} */
const safeListFile = 'safelist.txt';

// colors.indigo
const SAFELIST_COLORS = 'colors';

module.exports = {
  mode: 'jit',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}', './safelist.txt'],
  darkMode: 'class',
  theme: {
    fontFamily: {
      sans: [
        'Inter',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        '"Helvetica Neue"',
        'Arial',
        '"Noto Sans"',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      serif: [
        'ui-serif',
        'Georgia',
        'Cambria',
        '"Times New Roman"',
        'Times',
        'serif',
      ],
      mono: [
        'ui-monospace',
        'SFMono-Regular',
        'Menlo',
        'Monaco',
        'Consolas',
        '"Liberation Mono"',
        '"Courier New"',
        'monospace',
      ],
    },
    screens: {
      xs: '576',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
    extend: {
      typography: (theme) => ({
        DEFAULT: {
          css: {
            color: theme('colors.gray.500'),
            maxWidth: '65ch',
          },
        },
        invert: {
          css: {
            color: theme('colors.gray.400'),
          },
        },
      }),
      colors: {
        primary: '#343C6A',
        secondary: '#232323',
        lightGray: '#EDF1F7',
        textGray: '#718EBF',
        black: '#232323',
        lemonTint: '#FDF3CC',
        mainMastGold: '#BB9400',
        treacherousBlizzard: '#D9F9E6',
        pixelatedGrass: '#00903a',
        saltMountain: '#D7F9FD',
        enamelBlue: '#007E8C',
        husky: '#E1E7FD',
        ballBlue: '#26B4D3',
        smoulderingRed: '#CB3A32',
        washedBlack: '#21272A',
        suitBlue: '#2C3236',
        brilliance: '#fdfdfd',
        offWhite: '#f9fafb',
        black: '#000000',
        blackLacquer: '#3e3e3e',
        encore: '#6b7280',
        weatheredStone: '#c3c3c3',
        white: '#FFFFFF',
        forbiddenFruit: '#fb7b7b',
        dapperGreyhound: '#697077',
        neverything: '#121619',
        carbon: '#333333',
        boysenberryShadow: '#F2F4F8',
        lightGreen: '#00B8BA',
        cardBg: '#FBFBFB',
        dateBlack: '#42445D',
        cusGray: '#F1F1F1 !important',
        cgRed: '#E43D30',
        textGray: '#505357',
        textBlue: '#2175D9',
        inputColor: '#718EBF',
        inputBorder: '#DFEAF2',
        inputLabel: '#232323',
        inputBg: '#F5F7FA',
        lightYellow: '#FFF5D9',
        lightBlue: '#E7EDFF',
        lightGreen: '#DCFAF8',
      },
    },
  },
  plugins: [
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    require('./twSafelistGenerator')({
      path: safeListFile,
      patterns: [
        `text-{${SAFELIST_COLORS}}`,
        `bg-{${SAFELIST_COLORS}}`,
        `dark:bg-{${SAFELIST_COLORS}}`,
        `dark:hover:bg-{${SAFELIST_COLORS}}`,
        `dark:active:bg-{${SAFELIST_COLORS}}`,
        `hover:text-{${SAFELIST_COLORS}}`,
        `hover:bg-{${SAFELIST_COLORS}}`,
        `active:bg-{${SAFELIST_COLORS}}`,
        `ring-{${SAFELIST_COLORS}}`,
        `hover:ring-{${SAFELIST_COLORS}}`,
        `focus:ring-{${SAFELIST_COLORS}}`,
        `focus-within:ring-{${SAFELIST_COLORS}}`,
        `border-{${SAFELIST_COLORS}}`,
        `focus:border-{${SAFELIST_COLORS}}`,
        `focus-within:border-{${SAFELIST_COLORS}}`,
        `dark:text-{${SAFELIST_COLORS}}`,
        `dark:hover:text-{${SAFELIST_COLORS}}`,
        `h-{height}`,
        `w-{width}`,
      ],
    }),
    require('@tailwindcss/typography'),
  ],
};
